# name: CI/CD Pipeline

# on:
#   push:
#     branches: [main]

# jobs:
#   build-push-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check Out Repo
#         uses: actions/checkout@4.1.1

#       - name: Build Docker Image
#         run: docker build -t ghcr.io/${{ github.repository }}/cicd-test:v1 .

#       - name: Log in to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GHCR_PAT }}

#       - name: Push to GitHub Container Registry
#         run: docker push ghcr.io/${{ github.repository }}/cicd-test:v1

#       - name: SSH and Deploy on Server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.REGISTRY_USERNAME }}
#           password: ${{ secrets.REGISTRY_PASSWORD }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
#             docker pull ghcr.io/${{ github.repository }}/cicd-test:v1
#             docker stop cicd-test || true
#             docker rm cicd-test || true
#             docker run -d --name cicd-test -p 2000:2000 ghcr.io/${{ github.repository }}/cicd-test:v1



name: branch-deploy-test

on:
  push:
    branches: [main, master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: branch-deploy
      id: branch-deploy
      uses: github/branch-deploy@v8.1.1